name: Prettier Check

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  test:
    name: Prettier Check
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Run Prettier Check
        run: |
          yarn add prettier --prefix ./
          yarn style:check --prefix ./
        working-directory: ${{ env.working-directory }}
